# Generated by Django 6.0.4 on 2026-05-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_birthrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='is_active',
        ),
        migrations.AddField(
            model_name='household',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='relationship',
            field=models.CharField(choices=[('Son', 'Son'), ('Daughter', 'Daughter'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='birthrecord',
            unique_together={('household', 'name', 'dob', 'father_name', 'mother_name')},
        ),
    ]
