# Generated by Django 6.0.4 on 2026-05-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_household_is_active_household_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(default='Church CMS', max_length=200)),
                ('church_logo', models.ImageField(upload_to='site_logo/')),
            ],
        ),
    ]
