# Generated by Django 6.0.4 on 2026-05-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthrecord',
            name='relationship',
            field=models.CharField(max_length=50),
        ),
    ]
