# Generated by Django 6.0.4 on 2026-05-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_member_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthrecord',
            name='relationship',
            field=models.CharField(choices=[('Son', 'Son'), ('Daughter', 'Daughter'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='relationship',
            field=models.CharField(max_length=50),
        ),
    ]
