# Generated by Django 6.0.4 on 2026-05-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_banktransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'ordering': ['-date', '-id']},
        ),
    ]
